### ISSUE TITLE
This solution won't work with older React versions

### ISSUE THREAD

**Issue by simzer** [vizzuhq/vizzu-react-example#2]
There should be a note about which React version the guide is compatible with.
It uses 17+ now. 
Hooks were introduced in 16.8.

**Comment by simzer** [comment]
@korompaiistvan do you know by any chance the exact React version this guide is compatible with?

**Comment by korompaiistvan** [comment]
this only uses the built-in hooks introduced in 16.8 so anything above that will work. that means that any react project that's at least 5 years old can use this. (as react 16 was released in sept 2017 and minor versions contain no breaking changes) 
that said there are still valid reasons for using class components instead of hooks. unfortunately, i personally dont have any experience with class components and currently no time to figure it out either :(.
the main takeaways are the same though: there needs to be a ref to the parent container of vizzu and react shouldn't touch that container's contents.

mapbox-gl-js has similar challenges and they have a good docs site that handles classes and hooks in parallel https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/

**Comment by simzer** [comment]
Thanks, so for now I will just put a not into the guide that it is compatible with React 16.8 and above.

**Comment by korompaiistvan** [comment]
i think that's fair, but it's also implied in the npx create-react-app step which always uses a very recent react version.

**Comment by simzer** [comment]
Yeah, I think it's better to state it explicitly.
